from HEIST import *
from ᴀᴜɴᴇʀ import *
from Color import *
from PPPADADWDKMNCAQWNOPKNQWD import *
if ɢʟɛǟʍ.XERONOID in otoh:
    LOGS.info("")
    LOGS.info("")    
    time.sleep(3)                                   
    LOGS.info(booting)
    time.sleep(3)
    LOGS.info("")
    LOGS.info("➢🥮________Ӽɛʀօռօɨɖ engine is now going to start________🥮")
    LOGS.info("")
    LOGS.info("")
    LOGS.info("=|- *    🔥(       (   🔥(      ) 🔥(    (      🔥) (    (   (    (") 
    time.sleep(1)
    LOGS.info("=|- )    ) 🔥(  `   )\ 🔥)    )\🔥 ) )\ ) 🔥*   ) ( /( 🔥*   🔥*   ")
    time.sleep(1)
    LOGS.info("=|- ( 🔥/( ( 🔥/( )\🔥))( 🔥(()/(🔥(  ((🔥)/(((🔥)/` )  🔥/( )🔥/( ")
    time.sleep(1)
    LOGS.info("=|- )\(🔥)))\(🔥)((_)(🔥)\ /(_🔥))\ 🔥 /(_🔥))/(_)( 🔥)(_)((_🔥(_🔥")
    time.sleep(1)
    LOGS.info("=|- (🔥(_)\🔥((_)\🔥(_()🔥((_🔥(_))🔥((_)🔥(_))🔥(_))🔥(_🔥(_🔥(_🔥")
    time.sleep(1) 
    LOGS.info("=|- 🎧██╗░░██╗███████╗██████╗░░█████╗░███╗░░██╗░█████╗░██╗██████╗░🎧")
    time.sleep(1)
    LOGS.info("=|- 🎧╚██╗██╔╝██╔════╝██╔══██╗██╔══██╗████╗░██║██╔══██╗██║██╔══██╗🎧") 
    time.sleep(1)
    LOGS.info("=|- 🎧░╚███╔╝░█████╗░░██████╔╝██║░░██║██╔██╗██║██║░░██║██║██║░░██║🎧")
    time.sleep(1)
    LOGS.info("=|- 🎧░██╔██╗░██╔══╝░░██╔══██╗██║░░██║██║╚████║██║░░██║██║██║░░██║🎧")
    time.sleep(1)
    LOGS.info("=|- 🎧██╔╝╚██╗███████╗██║░░██║╚█████╔╝██║░╚███║╚█████╔╝██║██████╔╝🎧")
    time.sleep(1)
    LOGS.info("=|- 🎧╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝░╚════╝░╚═╝░░╚══╝░╚════╝░╚═╝╚═════╝░ 🎧")
    LOGS.info("")
    LOGS.info("")
    LOGS.info("=|- |   Ӽɛʀօռօɨɖ ♚ＲＥＡＤＹ♚  |")
    time.sleep(2) 
    LOGS.info("")  
    LOGS.info("=|- ɢᴇᴛᴛɪɴɢ ᴀʟʟ ꜰɪʟᴇꜱ ʀᴇᴀᴅʏ 📩")
    LOGS.info("")
    LOGS.info("=|- ꜱʏɴᴄɪɴɢ ᴅᴏɴᴇ 🧧")
    LOGS.info("=|  ᴍᴏᴠɪɴɢ ᴏɴ 🎏")
    time.sleep(1) 
    LOGS.info("=|- Checking ELEMENT Files 📨")
    time.sleep(3)
    LOGS.info("=|- ꜱʏɴᴄɪɴɢ ᴅᴏɴᴇ 🧧")
    LOGS.info("=|  ᴍᴏᴠɪɴɢ ᴏɴ 🎏")
    os.system("python3 haito.py")
else:
    LOGS.info("")
    LOGS.info("")
    LOGS.info("")
    LOGS.info("")
    LOGS.info("=|- ᗯᖇOᑎG 𝐗𝐄𝐑𝐎𝐍𝐎𝐈𝐃_𝐊𝐄𝐘 ᴏʀ ɴᴏ 𝐗𝐄𝐑𝐎𝐍𝐎𝐈𝐃_𝐊𝐄𝐘")
    time.sleep(2)
    LOGS.info("=|- ᴘʟᴇᴀꜱᴇ ᴄʜᴇᴄᴋ ʏᴏᴜʀ 𝐗𝐄𝐑𝐎𝐍𝐎𝐈𝐃_𝐊𝐄𝐘")
    time.sleep(2)
    LOGS.info("=|- ɴᴏᴡᴀʏ Ӽɛʀօռօɨɖ engine ᴄᴀɴ ʟᴇᴛ ʏᴏᴜ ᴄᴏɴᴛɪɴᴜᴇ!")
    time.sleep(2)
    LOGS.info("=|- ᴘᴜᴛ ᴛʜᴇ ᴄᴏʀʀᴇᴄᴛ 𝐗𝐄𝐑𝐎𝐍𝐎𝐈𝐃_𝐊𝐄𝐘 ᴀɴᴅ ʀᴇᴅᴇᴘʟᴏʏ ᴛʜᴇ ʙᴏᴛ.")
    time.sleep(2)
    LOGS.info("=|- ❗️ 𝐄𝐗𝐈𝐓𝐈𝐍𝐆 𝐀𝐍𝐃 𝐂𝐋𝐄𝐀𝐍𝐈𝐍𝐆 𝐄𝐍𝐓𝐈𝐑𝐄 𝐒𝐎𝐔𝐑𝐂𝐄-𝐂𝐎𝐃𝐄 ❗️")
    time.sleep(2)
    try:
        shutil.rmtree("PPPADADWDKMNCAQWNOPKNQWD")
        shutil.rmtree("VEhJU0lTVVNFREZPUlhFUk9OT0lE")
        shutil.rmtree("knite")
    except:
        LOGS.info("𝙈𝙖𝙣𝙪𝙖𝙡 𝙀𝙧𝙖𝙨𝙚 𝙤𝙧 𝙘𝙤𝙣𝙩𝙖𝙘𝙩 @HypeVoids or @HypeVoidSoul") 
        pass
    sys.exit()